# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://frankgerhardt.github.io',
                'git_url': 'https://github.com/frankgerhardt/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': { 'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py'),
                                        'nbdev_hello_world.core.say_hello': ('core.html#say_hello', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.nbdev_hello_world': { 'nbdev_hello_world.nbdev_hello_world.foo': ( 'core.html#foo',
                                                                                                  'nbdev_hello_world/nbdev_hello_world.py'),
                                                     'nbdev_hello_world.nbdev_hello_world.say_hello': ( 'core.html#say_hello',
                                                                                                        'nbdev_hello_world/nbdev_hello_world.py')}}}
